### PR TITLE
Fix for issue/task #253 (add new flags for isGroupManager and isGroupAdmin

### LINKED ISSUE #253: like the $scope.isSystemAdmin return flags for isGroupAdmin and isGroupManager
This will allow the Angular UI to properly handle conditional display settings for several aspects. Change will involve making the decision call in the REST API, returning it to angular, and setting $scope values based on the REST api response.

### PR DESCRIPTION
**Pull request by brentstineman**
fixes #253 by adding two new flags to the $scope.userprofile object returned by api/user. Also fixes a previously unreported issue with the 'creategroup' stored procedure whereby the user was not flagged as a manager of a group they just created in the user document

proof

### CODE REVIEW

File: DocDbSetup/SP_CreateGroup.js [hunk 1]
```diff
@@ -45,7 +45,8 @@ function (groupDoc) {
         // define group for group list
         var userFrag = {
             "id": groupDoc.id,
-            "name": groupDoc.name
+            "name": groupDoc.name,
+            "isManager" : "true"
```
Comment (brentstineman) [inline DocDbSetup/SP_CreateGroup.js]: This is not directly related to issue #253 but was found during testing and fixed. "isManager" was being set in the group document, but not in the user document.

File: DocumentDbRepositories/ScampUser.cs [hunk 2]
```diff
@@ -33,7 +32,7 @@ public ScampUser()
         [JsonProperty(PropertyName = "groupmbrship")]
         public List<ScampUserGroupMbrship> GroupMembership { get; set; }
 
-        [JsonProperty(PropertyName = "budget")]
+        [JsonProperty(PropertyName = "budget", NullValueHandling = NullValueHandling.Ignore)]
```
Comment (brentstineman) [inline DocumentDbRepositories/ScampUser.cs]: This was added to ensure proper serialization of a "null" budget value. By not serializing it, we reduce the RU cost of retrieving user documents that don't have a budget.

File: ScampApi/Controllers/GroupsUsersController.cs [hunk 3]
```diff
@@ -102,6 +102,9 @@ public GroupsUsersController(ISecurityHelper securityHelper, IGroupRepository gr
             if (userList.Count() > 0) // user is already in the list
                 return new ObjectResult("designated user is already a member of specified group") { StatusCode = 400 };
 
+            // create the user if they don't exist
+            //TODO: https://github.com/SimpleCloudManagerProject/SCAMP/issues/247
```
Comment (brentstineman) [inline ScampApi/Controllers/GroupsUsersController.cs]: placed this in to help with resolution of item #247 which is still outstanding.

**Comment by vjrantal** [comment]
Based on my testing, the new flags works as expected.

Going forward, I'd recommend writing commit messages based on, for example, a model from http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html. Too long first line makes it harder to read the message with certain tools.
